### ISSUE TITLE
Can't open posts in mobile

### ISSUE THREAD

**Issue by cristiantanase2016** [puikinsh/Dazzling#60]
See reference here:

https://colorlib.com/wp/forums/topic/cant-open-posts-in-mobile/#post-83942

Solution by Giucu:

Line 1085 trebuie scos:

 ```
.side-pull-left #primary {
   float: left;
}
```

**Comment by cristiantanase2016** [comment]
Another request: https://colorlib.com/wp/forums/topic/cant-open-woocommerce-product-page-on-mobiletablet/ 

Solution: need to be deleted also this css:
```
side-pull-right #primary {
    float: right;
}
```

**Comment by puikinsh** [comment]
This was fixed back in 2017 — the issue just never got closed. Sorry for leaving you without a reply.

Commit 46a6e05 applied exactly the change suggested in the linked thread: the `float` rules were wrapped in a breakpoint rather than applying at every width.

```css
@media (min-width: 992px) {
    .side-pull-left #primary  { float: left; }
    .side-pull-right #primary { float: right; }
}
```

So on phones the content column no longer floats and the posts are reachable. That fix is in every release from 2.1.0 onward, including the current 2.2.5.
